### ISSUE TITLE
Jobs are not running sometimes

### ISSUE THREAD

**Issue by hashweather** [hokify/agenda#25]
Thanks for porting this amazing library.

Please,I'm having a really serious issue in production.

Which is that sometimes Agenda doesn't run the Jobs and some other times it runs. This is really embarrassing as my users are so so angry already.

So, my question is at any random point in time is there a function I can call on agenda to know if it is still running or it has stopped?

Any ideas would be really appreciated.

**Comment by angelxmoreno** [comment]
If you are connected via mongodb I would suggest checking the status of the jobs there.do they have a `failReason` ?

**Comment by angelxmoreno** [comment]
An alternative to viewing the db is to run `npx agendash --db=mongodb://localhost/agendaDb --collection=agendaCollection --port=3002` (with the proper params of course ) . See more info here: https://github.com/agenda/agendash

For my situation, it seems that active jobs are set to completed upon restarting my agenda service.

**Comment by simllll** [comment]
@angelxmoreno are you using the @hokify/agenda? Because your issue sounds like a bug that is in the original fork (when agenda is shutting down, it does not correctly free up locked jobs)

@hashweather you can check getRunningStats() maybe even with true as first parametre, this helps debugging and finding reasons why a job is not picked up for example. But I guess it's a more common problem, and therefore I would recommend the answer of @angelxmoreno first to try agendash, it will maybe give you the right answer already! :-)

**Comment by stefdelec** [comment]
We do have the issue with @hokify/agenda.

**Comment by kunaldhaibar-leaptodigital** [comment]
I'm facing a similar issue where the job definition nor the on() method is executed when a job is scheduled. This is occurring randomly!

**Comment by simllll** [comment]
Still happening with v6? If so please create a new issue
