### ISSUE TITLE
What is the Most Efficient Way to use Agenda in Production

### ISSUE THREAD

**Issue by hashweather** [hokify/agenda#26]
I am using the NodeJS Agenda Scheduler and I wish to know a few things before going to production.

There are 3 scenarios

 1. A User called Peter wants to schedule a Message to be sent by 5PM on the Second of July 
    2022

 2. Another User called Mary wants to schedule a Message to be sent by 10PM on the 15th of 
    August 2022.
 
 For every new request to schedule a new message to be sent in the future I am creating a new Job for it using the function below
   

    defineNewJob(messageId, jobDate) {
        let jobName = `send_${messageId}`;
        try {
            agenda.define(jobName, jobHandler);
            await agenda.schedule(jobDate, jobName, { message_id: messageId, removeOnCompleted: true });
        } catch (e) {
            console.log(`Error Scheduling Job`);
        }
    }

 This means that I might end up with over 1 million messages from different users all to be scheduled in the future at completely different times and stored in the MongoDB database

  3. I noticed that when I restart my server, Agenda has lost all I scheduled so I need to read back the data from my database and call the function above again with each of the returned messages from my database. Is this an efficient way to do things? I don't think so.

Please currently the scheduling works flawlessly at the specified dates and time. I'm only concerned about the efficiency of this in production with a lot of users scheduling all kinds of messages at different dates and times.

So, Is this fine in production or do I need to make changes?

**Comment by simllll** [comment]
Hi @hashweather , agendaTS queries the mongodb every `processEvery` seconds to see if there are any jobs that will be run in the neat future (means current time + lock lifetime) .. if it does, it queues the jobs in the local queue and processes them as soon as the time has come :)

Regarding your implementation though: you shouldn't define a new agenda job definition for each message. because on restart you would need to reintialize all the job definitions.

Do something like this:
create only ONE job definition .. e.g.
agenda.define('send message', jobHandler);

everytime when you want to queue a new message, do what you do already, like:
        await agenda.schedule(jobDate, 'send message', { message_id: messageId, removeOnCompleted: true });


you pass in message_id and other parametrs already, so the jobHandler just gets the data from the job data.
e.g. 
```
function jobHandler(job) {
console.log(job.attrs.message_id);
}
```

So to keep the answer short: agenda does all the things that are necessary that you can have thousand of messages in the queue and only the ones that are relevant are "loaded" and executed just in time. but re use your definitions as much as possible, you shouldn't create new definitions during "runtime"..only create them once at the start of the server.

**Comment by xts-bit** [comment]
@ebitogu Did you fix your issue?
